module.exports = {
    menu: "💫",
    "bug menu": "🗡",
    "bug ultra menu": "⚔️",
    setmenu: "💫",
    "private mode": "💫",
    "public mode": "💫",
    Block: "💫",
    unblock: "💫",
    protection: "🛡",
    sudo: "💫",
    namebot: "💫",
    setprifixe: "💫",
    detect: "💫",
    botme: "💫",
    antipirate: "📵",
    autostatutview: "👁",
    autodownloadstatut: "📥",
    antidelectmessage: "🚫",
    presence: "👁",
    autoreactmessage: "😶‍🌫️",
    autoviewonce: "👁",
    infome: "💫",
    owner: "💫",
    "change my description": "🔄",
    signal: "‼️",
    "antibot privat": "💫",
    sendlink: "📲",
    "antisudo me": "💫",
    Tagall: "📣",
    "group close": "🔐",
    "group open": "🔓",
    promote: "💫",
    demote: "💫",
    link: "🙋",
    kick: "🪦",
    add: "➕️",
    kickall: "📣",
    Rlink: "🔄",
    antibot: "⛔️",
    antispam: "📴",
    join: "🔗",
    "kick me": "👤",
    antilink: "🔗",
    del: "🗑",
    "info group": "💫",
    welcome: "🤝",
    goodbye: "👋",
    group: "💫",
    groupname: "💫",
    setwelcome: "💫",
    testwelcome: "💫",
    setgoodbye: "💫",
    testgoodbye: "💫",
    hidetag: "🎤",
    antipromote: "💫",
    antidemote: "💫",
    Rdescription: "🔄",
    "bangroup comunity": "💫",
    searchBot: "🧭",
    purgescript: "☠️",
    "invite journaliste": "🕵‍♂️",
    antipurge: "🚨",
    "access group": "💫",
    "protect group": "💫",
    sondage: "💫",
    aprouvgroup: "💫",
    "aprouvgroup comunity": "💫",
    vv: "💫",
    take: "👨‍💻",
    sticker: "💫",
    photo: "💫",
    stickersearch: "💫",
    fancy: "💫",
    URL: "🔗",
    scrop: "💫",
    videostick: "💫",
    emox: "💫",
    apk: "💫",
    img: "📸",
    Google: "🌍",
    song: "📀",
    YouTube: "📺",
    vidéo: "💫",
    lyrics: "🎵",
    pinterest: "🌍",
    "édit logo": "💫",
    "Search logo": "🧭",
    "sticker logo": "💫",
    "logo nlg": "💫",
    "creat group": "💫",
    "creat comunity": "💫",
    "creat Chanel": "💫",
    hwaifu: "😑",
    trap: "😐",
    hneko: "🤨",
    blowjob: "🤐",
    hentaivid: "🧐",
    waifu: "😁",
    neko: "😆",
    shinobu: "😗",
    megumin: "😋",
    cosplay: "😙",
    couplepp: "😌",
    "!help": "💫",
    "!ping": "💫",
    "!info": "💫",
    "!weather": "🌤",
    "!meme": "💫",
    "!joke": "💫",
    botsystem: "🛰",
    reboot: "🚀",
    "créateurs the bot access": "🛑",
    reconnaissant: "👁",
    "kick admin principal": "😈"
};
